openapi: 3.0.1
info:
  title: Yet Another Job Board API
  version: "1.2"
paths:
  /api/account/admin/user/{userId}:
    get:
      tags:
      - account-admin
      operationId: peekAtUserAccount
      parameters:
      - name: yajb-tenant-token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserAccountResponse'
      security:
      - oidc: []
components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties:
            type: object
    AdvertId:
      type: object
      properties:
        guid:
          type: string
    ManagedJobAdvertSummary:
      required:
      - companyName
      - currentStatus
      - id
      - jobTitle
      type: object
      properties:
        id:
          $ref: '#/components/schemas/AdvertId'
        jobTitle:
          type: string
        companyName:
          type: string
        currentStatus:
          $ref: '#/components/schemas/Status'
    PaymentInfo:
      type: object
      properties:
        paymentLink:
          type: string
          format: uri
        paid:
          type: boolean
    Status:
      type: string
      enum:
      - Drafted
      - AwaitingPayment
      - SentForPublication
      - Published
      - Closing
      - Terminated
    Subscription:
      required:
      - initialPayment
      - plan
      type: object
      properties:
        plan:
          $ref: '#/components/schemas/SubscriptionPlan'
        initialPayment:
          $ref: '#/components/schemas/PaymentInfo'
    SubscriptionPlan:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        advertSlots:
          type: integer
          format: int32
        currencyCode:
          type: string
        priceInCents:
          type: integer
          format: int32
        interval:
          type: string
    SubscriptionSlots:
      type: object
      properties:
        available:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
    UserAccountResponse:
      required:
      - adverts
      - slots
      - stripeCustomerId
      - userId
      type: object
      properties:
        userId:
          type: string
        stripeCustomerId:
          type: string
        subscription:
          $ref: '#/components/schemas/Subscription'
        slots:
          $ref: '#/components/schemas/SubscriptionSlots'
        adverts:
          type: array
          items:
            $ref: '#/components/schemas/ManagedJobAdvertSummary'
  securitySchemes:
    oidc:
      type: http
      scheme: bearer
      bearerFormat: JWT
