openapi: 3.0.1
info:
  title: Yet Another Job Board API
  version: "1.3"
paths:
  /api/media/videos:
    get:
      tags:
        - media
      operationId: myVideos
      parameters:
        - name: yajb-tenant-token
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ManagedVideo'
      security:
        - oidc: []
  /api/media/videos/upload:
    get:
      tags:
        - media
      operationId: createVideoUpload
      parameters:
        - name: yajb-tenant-token
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UploadCoordinates'
      security:
        - oidc: []
  /api/media/images:
    get:
      tags:
        - media
      operationId: myImages
      parameters:
        - name: yajb-tenant-token
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ManagedImage'
      security:
        - oidc: []
  /api/media/images/upload:
    get:
      tags:
        - media
      operationId: createImageUpload
      parameters:
        - name: yajb-tenant-token
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UploadCoordinates'
      security:
        - oidc: []
components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties:
            type: object
    ManagedVideo:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        url:
          type: string
          format: uri
        thumbnailUrl:
          type: string
          format: uri
        duration:
          type: number
          format: double
        uploaded:
          type: string
          format: date-time
        transcodingProgressPercent:
          type: integer
          format: int32
        status:
          type: string
    UploadCoordinates:
      type: object
      properties:
        uploadUrl:
          type: string
          format: uri
        id:
          type: string
    ManagedImage:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        url:
          type: string
          format: uri
        uploaded:
          type: string
          format: date-time
  securitySchemes:
    oidc:
      type: http
      scheme: bearer
      bearerFormat: JWT
