openapi: 3.0.1
info:
  title: config | Yet Another Job Board API
  version: "1.0"
paths:
  /api/static-config:
    get:
      tags:
      - config
      operationId: staticConfig
      parameters:
      - name: yajb-tenant-token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StaticConfig'
components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties:
            type: object
    StaticConfig:
      required:
      - industries
      - roleTypes
      - seniorityLevels
      type: object
      properties:
        industries:
          type: array
          items:
            type: string
        roleTypes:
          type: array
          items:
            type: string
        seniorityLevels:
          type: array
          items:
            type: string
  securitySchemes:
    oidc:
      type: http
      scheme: bearer
      bearerFormat: JWT
