openapi: 3.0.1
info:
  title: video | Yet Another Job Board API
  version: "1.0"
paths:
  /api/videos/upload:
    post:
      tags:
      - video
      operationId: createUpload
      parameters:
      - name: yajb-tenant-token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadRequest'
        required: true
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UploadCoordinates'
      security:
      - oidc: []
  /api/videos:
    get:
      tags:
      - video
      operationId: myVideos
      parameters:
      - name: yajb-tenant-token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemDetail'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ManagedVideo'
      security:
      - oidc: []
components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties:
            type: object
    UploadRequest:
      type: object
      properties:
        title:
          type: string
    UploadCoordinates:
      type: object
      properties:
        uploadApiHost:
          type: string
          format: uri
        uploadToken:
          type: string
        videoId:
          type: string
    ManagedVideo:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        url:
          type: string
          format: uri
        thumbnailUrl:
          type: string
          format: uri
  securitySchemes:
    oidc:
      type: http
      scheme: bearer
      bearerFormat: JWT
